name: my_mart
description: "Simple mart project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

# --- PACKAGES --- #
dependencies:
  flutter:
    sdk: flutter

  # - Utility packages - #
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  intl: ^0.19.0
  logger: ^2.4.0
  url_launcher: ^6.3.1
  iconsax: ^0.0.8
  get: ^4.6.6
  get_storage: ^2.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
  
  # --- Images,Icons,Logos --- #
  assets:
    - assets/images/
    - assets/icons/
    - assets/logos/
  
  # --- Fonts --- #
  fonts:
    - family: Lufga
      fonts:
        - asset: assets/fonts/LufgaBlack.ttf
        - asset: assets/fonts/LufgaBold.ttf
        - asset: assets/fonts/LufgaExtraBold.ttf
        - asset: assets/fonts/LufgaMedium.ttf
        - asset: assets/fonts/LufgaRegular.ttf
        - asset: assets/fonts/LufgaSemiBold.ttf
